/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_icatchtek_smarthome_APPLog */

#ifndef _Included_com_icatchtek_smarthome_APPLog
#define _Included_com_icatchtek_smarthome_APPLog
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_icatchtek_smarthome_APPLog
 * Method:    openLog
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_icatchtek_smarthome_APPLog_openLog
  (JNIEnv *, jclass, jstring);




/*
 * Class:     com_icatchtek_smarthome_APPLog
 * Method:    writeLogE
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_icatchtek_smarthome_APPLog_writeLogE
  (JNIEnv *, jclass, jstring, jstring) ;

/*
 * Class:     com_icatchtek_smarthome_APPLog
 * Method:    writeLogW
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_icatchtek_smarthome_APPLog_writeLogW
  (JNIEnv *, jclass, jstring, jstring) ;

/*
 * Class:     com_icatchtek_smarthome_APPLog
 * Method:    writeLogI
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_icatchtek_smarthome_APPLog_writeLogI
  (JNIEnv *, jclass, jstring, jstring) ;

#ifdef __cplusplus
}
#endif
#endif
