/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_icatchtek_smarthome_LogConfig */

#ifndef _Included_com_icatchtek_smarthome_LogConfig
#define _Included_com_icatchtek_smarthome_LogConfig
#ifdef __cplusplus
extern "C" {
#endif
#undef com_icatchtek_smarthome_LogConfig_SDK_LOG
#define com_icatchtek_smarthome_LogConfig_SDK_LOG 0L
#undef com_icatchtek_smarthome_LogConfig_APP_LOG
#define com_icatchtek_smarthome_LogConfig_APP_LOG 1L
/*
 * Class:     com_icatchtek_smarthome_LogConfig
 * Method:    nativeSetPath
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_icatchtek_smarthome_LogConfig_nativeSetPath
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_icatchtek_smarthome_LogConfig
 * Method:    nativeSetEnable
 * Signature: (IZ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_icatchtek_smarthome_LogConfig_nativeSetEnable
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     com_icatchtek_smarthome_LogConfig
 * Method:    nativeSetOutScreen
 * Signature: (IZ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_icatchtek_smarthome_LogConfig_nativeSetOutScreen
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     com_icatchtek_smarthome_LogConfig
 * Method:    nativeSetOutFile
 * Signature: (IZ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_icatchtek_smarthome_LogConfig_nativeSetOutFile
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     com_icatchtek_smarthome_LogConfig
 * Method:    nativeSetLevel
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_icatchtek_smarthome_LogConfig_nativeSetLevel
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_icatchtek_smarthome_LogConfig
 * Method:    nativeSetFileSize
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_icatchtek_smarthome_LogConfig_nativeSetFileSize
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_icatchtek_smarthome_LogConfig
 * Method:    nativeSetLogStart
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_icatchtek_smarthome_LogConfig_nativeSetLogStart
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
